import { SnNodeSchema } from '../../../smart-nodes/dto';

export const SN_ARRAY_FUNCTION_NODE_SCHEMA: SnNodeSchema = {
    type: 'SnArrayFunctionNode' ,
    displayName: 'SN-ARRAY-FUNCTION',
    icon: 'fa-solid fa-f',
    flows: [],
    params: [{
        direction: 'out',
        key: 'result',
        types: ['string', 'number', 'date', 'time', 'datetime', 'boolean', 'so:', 'object', 'sys:'],
        dynamic: true,
        multiple: true,
        pluggable: true,
        master: true,
        displayName: 'SN-ARRAY-FUNCTION-RESULT',
    }, {
        direction: 'in',
        key: 'array',
        types: ['string', 'number', 'date', 'time', 'datetime', 'boolean', 'so:', 'object', 'sys:'],
        dynamic: true,
        multiple: true,
        pluggable: true,
        required: true,
        displayName: 'SN-ARRAY-FUNCTION-ENTRY-ARRAY',
    }, {
        key: 'function',
        direction: 'in',
        types: 'string',
        multiple: false,
        displayName: 'SN-ARRAY-FUNCTION-FUNCTION',
        pluggable: false,
        display: 'select',
        required: true,
    }],
    sections: [{
        key: 'parameters',
        displayName: 'SN-ARRAY-FUNCTION-PARAMETERS',
        open: true,
        editable: false,
        hidden: true,
        params: [{
            key: 'position',
            direction: 'in',
            types: 'number',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-POSITION',
            pluggable: true,
            display: 'input',
            required: false,
            default: 0
        }, {
            key: 'inspect',
            direction: 'in',
            types: ['string', 'number', 'date', 'time', 'datetime', 'boolean', 'so:', 'object', 'sys:'],
            multiple: true,
            displayName: 'SN-ARRAY-FUNCTION-INSPECTION-ARRAY',
            pluggable: true,
            required: false,
        }, {
            key: 'propKey',
            direction: 'in',
            types: 'string',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-PROPKEY',
            pluggable: true,
            display: 'select',
            required: false,
        },  {
            key: 'propType',
            direction: 'in',
            types: 'string',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-PROPTYPE',
            pluggable: true,
            display: 'select',
            required: false,
        },  {
            key: 'propValue',
            direction: 'in',
            types: 'string',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-PROPVALUE',
            pluggable: true,
            display: 'input',
            required: false,
        }, {
            key: 'order',
            direction: 'in',
            types: 'string',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-ORDER',
            pluggable: true,
            display: 'select',
            required: false,
            default: 'asc'
        }, {
            key: 'separator',
            direction: 'in',
            types: 'string',
            multiple: false,
            displayName: 'SN-ARRAY-FUNCTION-SEPARATOR',
            pluggable: true,
            display: 'input',
            required: false,
        }]
    }]
};
