import { ConnectionDto, EnvironmentDisplayDto, ObjectTreeLineDto } from '../../dtos';

export const DEFAULT_STUDIO_ENVIRONMENT:
    (
        smartmodelUuid: string,
        connection: ConnectionDto,
        apps: ObjectTreeLineDto[],
        workflows: ObjectTreeLineDto[],
        connectors: ObjectTreeLineDto[],
        reports: ObjectTreeLineDto[],
    ) => EnvironmentDisplayDto = (
        smartmodelUuid: string,
        connection: ConnectionDto,
        apps: ObjectTreeLineDto[],
        workflows: ObjectTreeLineDto[],
        connectors: ObjectTreeLineDto[],
        reports: ObjectTreeLineDto[]
    ) => ({
        customerKey: connection.customerKey,
        host: connection.host,
        name: connection.name,
        modules: [{
            refUuid: '0ec891e7-5b2b-4c8c-a628-4358343fb54c',
            class: 'modules',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-cubes',
            name: 'EXPLORER-DATA',
            state: false,
            childs: [{
                refUuid: smartmodelUuid,
                type: 'smartmodel',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-MODELER',
                state: false,
                childs: [],
            }, {
                refUuid: 'bcb5f987-fe5a-4d2c-9360-edc5bd4ef767',
                type: 'database',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-DATABASE',
                state: false,
                childs: [],
            }, {
                hidden: false,
                refUuid: 'e29793dd-3df7-4d8a-954d-63acb6b13694',
                type: 'listgen',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-LIST',
                state: false,
                childs: [],
            }, {
                hidden: false,
                refUuid: 'e29asd3dd-3df7-4d8a-954d-63acb6b13ca4',
                type: 'metadata',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-METADATA',
                state: false,
                childs: [],
            }, {
                hidden: false,
                refUuid: 'fd9bc08a-004f-4605-94df-f0065993206f',
                type: 'tags',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-TAGS',
                state: false,
                childs: [],
            }, {
                hidden: false,
                refUuid: '41e53f71-883b-4206-9746-229a7aa45fe4',
                type: 'import',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-IMPORT',
                state: false,
                childs: [],
            }]
        }, {
            hidden: false,
            refUuid: '1ab87866-9310-4f3c-a657-c52e0f2a79c9',
            type: 'applications',
            class: 'modules',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-window-maximize',
            name: 'EXPLORER-APPLICATIONS',
            state: false,
            childs: [{
                hidden: false,
                refUuid: '2f4a47cb-82c4-4f1f-a1b0-bd6d59160896',
                type: 'app',
                class: 'objects',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-UI-COMPOSER',
                state: false,
                childs: apps,
            }, {
                hidden: false,
                refUuid: 'f86ed10b-2c0f-4f54-967e-36aefa695a3e',
                type: 'appSettings',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'SETTINGS.APPLICATIONS',
                state: false,
                childs: [],
            }],
        }, {
            refUuid: '5879c53d-c803-45be-a525-e3f3a01adfbd',
            type: 'workflow',
            class: 'objects',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-diagram-project',
            name: 'EXPLORER-WORKFLOWS',
            state: false,
            childs: workflows
        }, {
            refUuid: '5ac00b3b-189f-4a0c-8bed-3fb2029e79c1',
            class: 'modules',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-atom',
            name: 'EXPLORER-APISATION',
            state: false,
            childs: [{
                refUuid: 'ff8e55b8-72e5-40d7-a3c6-4edd1e5ed737',
                type: 'smartflow',
                class: 'objects',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-CONNECTORS',
                state: false,
                childs: connectors,
            }, {
                hidden: false,
                refUuid: 'a2f09ae9-8c0f-45b3-909f-f0a83c1f7152',
                type: 'task',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-TASKS',
                state: false,
                childs: [],
            }]
        }, {
            refUuid: 'c0f4f1e8-0038-4ab4-8d5d-7b5380f3d84c',
            type: 'report',
            class: 'objects',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-file-lines',
            name: 'EXPLORER-REPORTS',
            state: false,
            childs: reports,
        }, {
            refUuid: '1a8b0648-5f4b-4c2f-93c3-2f7e608e9860',
            type: 'i18n',
            class: 'module',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-earth-europe',
            name: 'EXPLORER-I18N',
            state: false,
            childs: [],
        }, {
            hidden: false,
            refUuid: '87e64b9c-ba4e-4984-a071-3820e82786e0',
            class: 'modules',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-cog',
            name: 'EXPLORER-SETTINGS',
            state: false,
            childs: [
                {
                    refUuid: '8a0bab62-9708-44ac-857e-ff3b33e8bba1',
                    type: 'theme',
                    class: 'module',
                    customerKey: connection.customerKey,
                    host: connection.host,
                    name: 'EXPLORER-THEME',
                    state: false,
                    childs: [],
                }, {
                    refUuid: '8a0bab62-9708-44ac-857e-ff3b33e8bba2',
                    type: 'check',
                    class: 'module',
                    customerKey: connection.customerKey,
                    host: connection.host,
                    name: 'EXPLORER-TRACKING-SETTINGS',
                    state: false,
                    childs: [],
                }, {
                    refUuid: '8a0bab62-9708-44ac-857e-ff3b33e8bba3',
                    type: 'manifest',
                    class: 'module',
                    customerKey: connection.customerKey,
                    host: connection.host,
                    name: 'EXPLORER-PLAYER-MANIFEST',
                    state: false,
                    childs: [],
                }
            ],
        },
        {
            hidden: false,
            refUuid: '7f62fd2a-0c37-4a34-abfc-894f79de62e6',
            class: 'modules',
            customerKey: connection.customerKey,
            host: connection.host,
            icon: 'fa-solid fa-shield-alt',
            name: 'EXPLORER-SECURITY',
            state: false,
            childs: [{
                refUuid: 'b755c252-4aa2-4d69-8ecd-1d5820ece778',
                type: 'groups',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-GROUPS',
                state: false,
                childs: [],
            },
            {
                refUuid: '8cae904e-dede-4e17-9941-40e382c5067f',
                type: 'users',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-USERS',
                state: false,
                childs: [],
            },
            {
                refUuid: '8cae904e-ded1-4e17-9941-40e382c50678',
                type: 'audit-trail',
                class: 'module',
                customerKey: connection.customerKey,
                host: connection.host,
                name: 'EXPLORER-AUDIT-TRAIL',
                state: false,
                childs: [],
            }
            ],
        }
        ]
    });
